server:
  port: 8080

spring:
  application:
    name: protocol-sl651-boot
  rabbitmq:
    host: 192.168.1.241
    port: 30004
    username: protocol_sl651_admin #???
    password: protocol_sl651_admin #??
    virtual-host: protocol_sl651   #?????
    #???????
    #???????????(Exchange)
    publisher-confirm-type: correlated
    #??????????(Queue)
    publisher-returns: true

sl651:
  # netty??
  netty:
    port: 8651
    # ???????
    max-frame-length: 4112
    # ????????
    publisher-exchange: "sl651.exchange"
    # ??????
    publisher-routing-key: "sl651.publisher"
    # ???????
    publisher-delay: 86400000
    # ???????
    hourReportDisplay: false
    # ???????
    regularReportDisplay: true
    # ???????
    overtimeReportDisplay: false
    # ??????
    hunanTransfer: true
    # ???
    diff-minute: 70
    # ??????(??)
    message-minutes-expiration: 60
    # ??????
    distribute-routes: false
    # ??????????
    old-data-forward-routes: false
  property:
    limits:
      # ?????
      - {code: "20", open: 0, close: 500}
      # 5?????
      - {code: "22", open: 0, close: 30}
      # 1?????
      - {code: "1a", open: 0, close: 305}
      # 3?????
      - {code: "1c", open: 0, close: 500}
      # 6?????
      - {code: "1d", open: 0, close: 500}
      # 12?????
      - {code: "1e", open: 0, close: 500}
      # ????
      - {code: "1f", open: 0, close: 500}
